-- AlterTable
ALTER TABLE "Salary" ALTER COLUMN "advanceDeduction" SET DEFAULT 0,
ALTER COLUMN "bonuses" SET DEFAULT 0,
ALTER COLUMN "deductions" SET DEFAULT 0,
ALTER COLUMN "status" SET DEFAULT 'PENDING';
